apiVersion: v1
kind: Template
metadata:
  name: "apicast-failing-policy"
message: "APIcast Failing Policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: apicast-policy

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: amp-apicast-custom-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: apicast-failing-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apicast-policy:failing
    source:
      git:
        uri: https://gitlab.cee.redhat.com/3scale-qe/apicast-failing-policy.git
        ref: 'master'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast-custom-policy
    name: apicast-custom-policies
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'amp-apicast-custom-policy:latest'
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        - bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: 'apicast-policy:failing'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/failing
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src

    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'
      type: Docker
    triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: AMP_RELEASE
  required: true
  description: AMP Version (eg. 2.2.0-GA)
